-- MySQL Script generated by MySQL Workbench
-- lun. 05 déc. 2016 14:39:07 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `agence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agence` (
  `age_id` INT NOT NULL AUTO_INCREMENT,
  `age_rue` VARCHAR(255) NOT NULL,
  `age_ville` VARCHAR(255) NOT NULL,
  `age_cp` VARCHAR(5) NOT NULL,
  `age_fax` VARCHAR(10) NULL,
  `age_mail` VARCHAR(255) NOT NULL,
  `age_nom` VARCHAR(45) NOT NULL,
  `age_telephone` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`age_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salarie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salarie` (
  `sal_id` INT NOT NULL AUTO_INCREMENT,
  `sal_date_embauche` DATE NOT NULL,
  `sal_date_naissance` DATE NOT NULL,
  `sal_rue` VARCHAR(255) NOT NULL,
  `sal_ville` VARCHAR(255) NOT NULL,
  `sal_cp` VARCHAR(5) NOT NULL,
  `sal_nom` VARCHAR(45) NOT NULL,
  `sal_prenom` VARCHAR(45) NOT NULL,
  `sal_permis` VARCHAR(2) NULL,
  `sal_chef` TINYINT(1) NOT NULL,
  `sal_experience` VARCHAR(255) NULL,
  `sal_agence` INT NOT NULL,
  `sal_login` VARCHAR(255) NOT NULL,
  `sal_mdp` VARCHAR(255) NOT NULL,
  `sal_etat` VARCHAR(2) NOT NULL DEFAULT 'V',
  `sal_tel` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`sal_id`),
  FOREIGN KEY (`sal_agence`)
    REFERENCES `agence` (`age_id`))
    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arret_maladie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arret_maladie` (
  `arr_id` INT NOT NULL AUTO_INCREMENT,
  `arr_date_debut` DATE NOT NULL,
  `arr_date_fin` DATE NOT NULL,
  `arr_motif` VARCHAR(45) NULL,
  `arr_sal` INT NOT NULL,
  PRIMARY KEY (`arr_id`),
    FOREIGN KEY (`arr_sal`)
    REFERENCES `salarie` (`sal_id`))
    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commercial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commercial` (
  `com_experience` VARCHAR(45) NOT NULL,
  `com_sal` INT NOT NULL,
  PRIMARY KEY (`com_sal`),
    FOREIGN KEY (`com_sal`)
    REFERENCES `salarie` (`sal_id`))
    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `motif_conge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motif_conge` (
  `mot_id` INT NOT NULL AUTO_INCREMENT,
  `mot_libelle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`mot_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conge` (
  `con_id` INT NOT NULL AUTO_INCREMENT,
  `con_date_debut` DATE NOT NULL,
  `con_date_fin` DATE NOT NULL,
  `con_date_reponse` DATE NOT NULL,
  `con_etat_demande` VARCHAR(3) NOT NULL DEFAULT 'ATT',
  `con_sal` INT NOT NULL,
  `con_motif` INT NOT NULL,
  PRIMARY KEY (`con_id`),
    FOREIGN KEY (`con_sal`)
    REFERENCES `salarie` (`sal_id`),   
    FOREIGN KEY (`con_motif`)
    REFERENCES `motif_conge` (`mot_id`))
    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage` (
  `gar_id` INT NOT NULL AUTO_INCREMENT,
  `gar_nom` VARCHAR(45) NOT NULL,
  `gar_rue` VARCHAR(255) NOT NULL,
  `gar_ville` VARCHAR(255) NOT NULL,
  `gar_cp` VARCHAR(5) NOT NULL,
  `gar_telephone` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`gar_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehicule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicule` (
  `veh_id` INT NOT NULL AUTO_INCREMENT,
  `veh_libelle` VARCHAR(255) NOT NULL,
  `veh_agence` INT NOT NULL,
  `veh_etat` VARCHAR(2) NOT NULL DEFAULT 'V',
  PRIMARY KEY (`veh_id`),
    FOREIGN KEY (`veh_agence`)
    REFERENCES `agence` (`age_id`))
    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immobilisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immobilisation` (
  `imm_id` INT NOT NULL AUTO_INCREMENT,
  `imm_type` VARCHAR(1) NOT NULL,
  `imm_date_debut` DATE NOT NULL,
  `imm_date_fin` DATE NULL,
  `imm_garage` INT NULL,
  `imm_vehicule` INT NOT NULL,
  PRIMARY KEY (`imm_id`),
    FOREIGN KEY (`imm_garage`)
    REFERENCES `garage` (`gar_id`), 
    FOREIGN KEY (`imm_vehicule`)
    REFERENCES `vehicule` (`veh_id`))
    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demenageur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demenageur` (
  `dem_chef` TINYINT(1) NOT NULL,
  `dem_permis` VARCHAR(45) NOT NULL,
  `dem_sal` INT NOT NULL,
  PRIMARY KEY (`dem_sal`),
    FOREIGN KEY (`dem_sal`)
    REFERENCES `salarie` (`sal_id`))
    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dossier_demenagement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dossier_demenagement` (
  `dos_numero` INT NOT NULL AUTO_INCREMENT,
  `dos_chargement_rue` VARCHAR(255) NOT NULL,
  `dos_chargement_ville` VARCHAR(255) NOT NULL,
  `dos_chargement_cp` VARCHAR(5) NOT NULL,
  `dos_livraison_rue` VARCHAR(255) NOT NULL,
  `dos_livraison_ville` VARCHAR(255) NOT NULL,
  `dos_livraison_cp` VARCHAR(5) NOT NULL,
  `dos_date_cloture` DATE NOT NULL,
  `dos_date_debut_dem` DATE NOT NULL,
  `dos_date_fin_dem` DATE NOT NULL,
  `dos_date_ouverture` DATE NOT NULL,
  `dos_etat_dossier` VARCHAR(45) NOT NULL,
  `dos_nb_demenageurs` VARCHAR(45) NOT NULL,
  `dos_nombre_km` VARCHAR(45) NOT NULL,
  `dos_volume` INT NOT NULL,
  `dos_agence` INT NOT NULL,
  `dos_commercial` INT NOT NULL,
  `dos_chefEquipe` INT NOT NULL,
  PRIMARY KEY (`dos_numero`),
    FOREIGN KEY (`dos_agence`)
    REFERENCES `agence` (`age_id`),
    FOREIGN KEY (`dos_commercial`)
    REFERENCES `commercial` (`com_sal`),
    FOREIGN KEY (`dos_chefEquipe`)
    REFERENCES `demenageur` (`dem_sal`))
    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permis` (
  `per_id` INT NOT NULL AUTO_INCREMENT,
  `per_libelle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`per_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `obtention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obtention` (
  `obt_date` DATE NOT NULL,
  `obt_sal` INT NOT NULL,
  `obt_permis` INT NOT NULL,
  PRIMARY KEY (`obt_sal`, `obt_permis`),
    FOREIGN KEY (`obt_sal`)
    REFERENCES `salarie` (`sal_id`),
    FOREIGN KEY (`obt_permis`)
    REFERENCES `permis` (`per_id`))
    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `utiliser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utiliser` (
  `uti_dossier` INT NOT NULL,
  `uti_vehicule` INT NOT NULL,
  PRIMARY KEY (`uti_dossier`, `uti_vehicule`),
    FOREIGN KEY (`uti_dossier`)
    REFERENCES `dossier_demenagement` (`dos_numero`),
    FOREIGN KEY (`uti_vehicule`)
    REFERENCES `vehicule` (`veh_id`))
    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `participer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `participer` (
  `par_demenageur` INT NOT NULL,
  `par_dossier` INT NOT NULL,
  PRIMARY KEY (`par_demenageur`, `par_dossier`),
    FOREIGN KEY (`par_demenageur`)
    REFERENCES `demenageur` (`dem_sal`),
    FOREIGN KEY (`par_dossier`)
    REFERENCES `dossier_demenagement` (`dos_numero`))
    
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
